import { gql } from 'apollo-boost'

export const GET_LESSONS = gql`
  query getLessons{
    lessons{
      id
      users{
        id
        firstName
        lastName
      }
      lessonsDay{
        id
        lesson{
          id
        }
        teacher{
          id
          user{
            firstName
            lastName
          }
        }
        users{
          id
        }
        dayDate
        hour{
          begin 
          end
        }
        spotLeft
        spotTotal
        isCanceled
      }
      lessonType{
        id
        name
        simpleName
        compatibilities{
          id
        }
      }
      lessonSubType{
        id
        name
        simpleName
      }
      discount
      name
      comment
      address{
        street
        city
        postalCode
      }
      pricing{
        unitPrice
        unitPrice2X
        unitPrice3X
        monthlyPrice
        monthlyPrice2X
        monthlyPrice3X
        totalPrice
        totalPrice2X
        totalPrice3X
      }
      totalMonth
      totalLessons
      classicDate
      priorityDate
      recurenceBegin
      recurenceEnd
      spotLeft
      spotTotal
      mainType
      dateType
      isOpened
    }
  }
`

export const GET_LESSONS_WAITING_OR_GOING = gql`
  query getLessonsWaitingOrGoing{
    lessonsWaitingOrGoing{
      id
      users{
        id
        firstName
        lastName
      }
      lessonsDay{
        id
        lesson{
          id
        }
        teacher{
          id
          user{
            firstName
            lastName
          }
        }
        users{
          id
        }
        dayDate
        hour{
          begin 
          end
        }
        spotLeft
        spotTotal
        isCanceled
      }
      lessonType{
        id
        name
        simpleName
        compatibilities{
          id
        }
      }
      lessonSubType{
        id
        name
        simpleName
      }
      discount
      name
      status
      comment
      address{
        street
        city
        postalCode
      }
      pricing{
        unitPrice
        unitPrice2X
        unitPrice3X
        monthlyPrice
        monthlyPrice2X
        monthlyPrice3X
        totalPrice
        totalPrice2X
        totalPrice3X
      }
      totalMonth
      totalLessons
      classicDate
      priorityDate
      recurenceBegin
      recurenceEnd
      spotLeft
      spotTotal
      mainType
      dateType
      isOpened
    }
  }
`